// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kturvbifwbaewqsgaanu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0dXJ2Ymlmd2JhZXdxc2dhYW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NzUwNTMsImV4cCI6MjA3MTU1MTA1M30.sq2bMQZ_ag5_0PNtJHWPFaV13MonjiP6-f1ApJSrAsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});